blank_issues_enabled: false
contact_links:
  - name: Blog Post Workflow Community Support
    url: https://github.com/ePlus-DEV/blog-post-workflow@v1/discussions
    about: You can ask and answer the questions here
